### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by vitacell** [chrippa/ds4drv#184]
Looks like the normal python cancer:

bash-4.3$ ds4drv
Traceback (most recent call last):
  File "/usr/bin/ds4drv", line 9, in <module>
    load_entry_point('ds4drv==0.5.0', 'console_scripts', 'ds4drv')()
  File "/usr/lib64/python2.7/site-packages/ds4drv/__main__.py", line 355, in main
    options = load_options()
  File "/usr/lib64/python2.7/site-packages/ds4drv/__main__.py", line 334, in load_options
    parse_uinput_mapping(name, mapping)
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 386, in parse_uinput_mapping
    mouse=mouse, mouse_options=mouse_options)
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 41, in create_mapping
    mouse = {getattr(ecodes, k): v for k,v in mouse.items()}
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 41, in <dictcomp>
    mouse = {getattr(ecodes, k): v for k,v in mouse.items()}
AttributeError: 'module' object has no attribute 'REL_WHEELDOWN'

bash-4.3$ ds4drv --hidraw
Traceback (most recent call last):
  File "/usr/bin/ds4drv", line 9, in <module>
    load_entry_point('ds4drv==0.5.0', 'console_scripts', 'ds4drv')()
  File "/usr/lib64/python2.7/site-packages/ds4drv/__main__.py", line 355, in main
    options = load_options()
  File "/usr/lib64/python2.7/site-packages/ds4drv/__main__.py", line 334, in load_options
    parse_uinput_mapping(name, mapping)
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 386, in parse_uinput_mapping
    mouse=mouse, mouse_options=mouse_options)
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 41, in create_mapping
    mouse = {getattr(ecodes, k): v for k,v in mouse.items()}
  File "/usr/lib64/python2.7/site-packages/ds4drv/uinput.py", line 41, in <dictcomp>
    mouse = {getattr(ecodes, k): v for k,v in mouse.items()}
AttributeError: 'module' object has no attribute 'REL_WHEELDOWN'

**Comment by DethByte64** [comment]
Execute like this: 

python3 ds4drv

Its trying to execute in bash.

**Comment by albfan** [comment]
Trace shows it is not running as bash, but as python.

ecodes is from evdev so probably this is an error with evdev module.
