### ISSUE TITLE
DS4 connects, shortly crashes

### ISSUE THREAD

**Issue by lunarcloud** [chrippa/ds4drv#31]
It connected, but ignored my configuration ( in /etc/), then crashed after trying to launch Steam Big Picture.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 132, in run
    self.loop.run()
  File "build/bdist.linux-x86_64/egg/ds4drv/eventloop.py", line 102, in run
    callback()
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 119, in read_report
    report = self.device.read_report()
  File "build/bdist.linux-x86_64/egg/ds4drv/backends/bluetooth.py", line 47, in read_report
    ret = self.int_sock.recv_into(self.buf)
error: [Errno 110] Connection timed out
```

The joystick device lingered for a bit, and will stay a phantom device if I dont wait for it to dissapear before restarting ds4drv.
Upon restart, the controller connects and understands the config.

**Comment by Ape** [comment]
Does this still occur?
